### ISSUE TITLE
Running Win-fpm

### ISSUE THREAD

**Issue by pwhodges** [andkrau/WIN-FPM#2]
Your previous reply shows an example of running win-fpm.exe.  Two things arise:

Where is win-fpm.exe, or how do I make it from win-fpm.tcl?

Can the suggested command line be run as a service, using (say) nssm?

Paul

**Comment by andkrau** [comment]
You can download a Windows binary here: https://github.com/andkrau/WIN-FPM/releases/tag/v2.0.0

Yes, nssm should work. It would restart the process if the PHP processes fail.

**Comment by pwhodges** [comment]
Thanks - I don't know why I couldn't find it before.


Anyway, I have now got it working (using nssm), and it has made a big improvement in one troublesome web site (and none in another, thus proving I have a different issue there...).


Paul

**Comment by pwhodges** [comment]
PS - the Caddy2 syntax is:


php_fastcgi {

        to localhost:9001
        to localhost:9002
        to localhost:9003
        to localhost:9004
        to localhost:9005
        to localhost:9006
        to localhost:9007
        to localhost:9008
}


You can also list them all on one line with no braces, but this form looks better to me


Paul

**Comment by andkrau** [comment]
Glad it helped performance. I've updated the readme with the caddy 2 example.
